Repository CAFECA-IO/iSunFA, pull requests merged in 2024-07, with the labels that each got.

#1305 Feature/account to repo
  package.json
  prisma/migrations/0_init/migration.sql
  prisma/schema.prisma
  prisma/seed_json/account.json
  src/lib/utils/formatter/account.formatter.ts
  src/lib/utils/repo/account.repo.ts
  src/pages/api/v1/company/[companyId]/account/[accountId]/index.test.ts
  src/pages/api/v1/company/[companyId]/account/[accountId]/index.ts
  src/pages/api/v1/company/[companyId]/account/index.test.ts
  src/pages/api/v1/company/[companyId]/account/index.ts
Labels: bug, 8

#1320 Feature/balance sheet
  package.json
  src/constants/account.ts
  src/constants/account_sheet_mapping/balance_sheet_mapping.json
  src/interfaces/accounting_account.ts
  src/interfaces/line_item.ts
  src/lib/utils/account.ts
  src/lib/utils/common.ts
  src/lib/utils/repo/line_item.repo.ts
  src/lib/utils/type_guard/account.ts
  src/pages/api/v1/company/[companyId]/report_financial/index.ts
  src/pages/api/v1/company/[companyId]/report_financial/status.ts
Labels: enhancement, 5

#1333 Feature/income statement
  package.json
  prisma/seed_json/account.json
  src/constants/account_sheet_mapping/balance_sheet_mapping.json
  src/constants/account_sheet_mapping/income_statement_mapping.json
  src/lib/utils/account.ts
  src/pages/api/v1/company/[companyId]/report_financial/index.ts
Labels: enhancement, 8

#1400 income statement update net income
  package.json
  src/interfaces/voucher.ts
  src/lib/utils/account.ts
  src/lib/utils/repo/invoice.repo.ts
  src/lib/utils/repo/ocr.repo.ts
  src/pages/api/v1/company/[companyId]/invoice/index.ts
  src/pages/api/v1/company/[companyId]/ocr/index.test.ts
  src/pages/api/v1/company/[companyId]/ocr/index.ts
  src/pages/api/v1/company/[companyId]/report_financial/index.ts
  src/pages/api/v1/company/[companyId]/voucher/[voucherId]/index.ts
  src/pages/api/v1/company/[companyId]/voucher/index.ts
Labels: enhancement, 2

#1404 Feature/i18n
  package.json
  src/components/add_project_modal/add_project_modal.tsx
  src/components/dashboard_bookmark/dashboard_bookmark.tsx
  src/components/edit_bookmark_modal/edit_bookmark_modal.tsx
  src/components/journal_list_body/journal_list_body.tsx
  src/components/my_reports_section/my_reports_section.tsx
  src/components/project_progress_chart/project_progress_chart.tsx
  src/lib/utils/auth_check.ts
  src/locales/cn/common.json
  src/locales/en/common.json
  src/locales/tw/common.json
Labels: enhancement, 2

#1408 Handcrafted formula of cash flow from operating activity by indirect method
  package.json
  prisma/seed_json/account.json
  src/constants/operating_cash_flow.ts
  src/interfaces/accounting_account.ts
  src/lib/utils/account.ts
  src/pages/api/v1/company/[companyId]/ask_ai/[resultId]/index.repository.ts
Labels: enhancement, 8

#1447 Feature/get indirect finaincial report
  package.json
  prisma/seed.ts
  prisma/seed_json/journal.json
  prisma/seed_json/line_item.json
  prisma/seed_json/voucher.json
  src/constants/operating_cash_flow.ts
  src/interfaces/cash_flow.ts
  src/lib/utils/account.ts
  src/lib/utils/financial_report/balance_sheet_generator.ts
  src/lib/utils/financial_report/cash_flow_statement_generator.ts
  src/lib/utils/financial_report/financial_report_generator.ts
  src/lib/utils/financial_report/financial_report_generator_factory.ts
  src/lib/utils/financial_report/income_statement_generator.ts
  src/lib/utils/repo/line_item.repo.ts
  src/pages/api/v1/company/[companyId]/report_financial/index.ts
  tsconfig.json
Labels: enhancement, 8

#1469 Feature/get indirect finaincial report
  package.json
  src/constants/cash_flow/investing_cash_flow.ts
  src/constants/cash_flow/operating_cash_flow.ts
  src/interfaces/cash_flow.ts
  src/interfaces/voucher.ts
  src/lib/utils/financial_report/cash_flow_statement_generator.ts
  src/lib/utils/financial_report/financial_report_generator.ts
  src/lib/utils/financial_report/financial_report_generator_factory.ts
  src/lib/utils/repo/voucher.repo.ts
  src/pages/api/v1/company/[companyId]/report_financial/index.ts
Labels: enhancement, 8

#1524 Feature/financial direct
  .eslintrc.js
  package.json
  prisma/seed_json/journal.json
  prisma/seed_json/line_item.json
  prisma/seed_json/voucher.json
  src/constants/cash_flow/common_cash_flow.ts
  src/constants/cash_flow/financing_cash_flow.ts
  src/constants/cash_flow/investing_cash_flow.ts
  src/constants/cash_flow/operating_cash_flow.ts
  src/interfaces/voucher.ts
  src/lib/utils/financial_report/cash_flow_statement_generator.ts
  src/lib/utils/financial_report/financial_report_generator.ts
  src/lib/utils/repo/voucher.repo.ts
  src/pages/api/v1/company/[companyId]/salary/[salaryId]/index.ts
Labels: enhancement, 8

#1550 Feature/create report
  package.json
  prisma/migrations/0_init/migration.sql
  prisma/schema.prisma
  prisma/seed_json/generated_report.json
  prisma/seed_json/pending_report.json
  src/constants/account.ts
  src/constants/report.ts
  src/interfaces/report.ts
  src/lib/utils/common.ts
  src/lib/utils/financial_report/balance_sheet_generator.ts
  src/lib/utils/financial_report/cash_flow_statement_generator.ts
  src/lib/utils/financial_report/financial_report_generator.ts
  src/lib/utils/financial_report/financial_report_generator_factory.ts
  src/lib/utils/financial_report/income_statement_generator.ts
  src/lib/utils/repo/report.repo.ts
  src/lib/utils/type_guard/account.ts
  src/lib/utils/type_guard/report.ts
  src/pages/api/v1/company/[companyId]/report/[reportId]/index.test.ts
  src/pages/api/v1/company/[companyId]/report/[reportId]/index.ts
  src/pages/api/v1/company/[companyId]/report_financial/index.ts
  src/pages/users/reports/analyses/view/[reportId].tsx
  src/pages/users/reports/financials/view/[reportId].tsx
Labels: enhancement, 5

#1594 Feature/get reports
  package.json
  src/components/project_report_page_body/project_report_page_body.tsx
  src/components/salary_record_form/salary_record_form.tsx
  src/constants/account_sheet_mapping/balance_sheet_lite_mapping.json
  src/constants/account_sheet_mapping/cash_flow_statement_lite_mapping.json
  src/constants/account_sheet_mapping/income_statement_lite_mapping.json
  src/constants/report.ts
  src/interfaces/report.ts
  src/interfaces/report_item.ts
  src/interfaces/report_type.ts
  src/lib/utils/formatter/report.formatter.ts
  src/lib/utils/repo/ocr.repo.ts
  src/lib/utils/repo/report.repo.ts
  src/lib/utils/type_guard/report.ts
  src/pages/api/v1/company/[companyId]/ask_ai/[resultId]/index.repository.ts
  src/pages/api/v1/company/[companyId]/ocr/[resultId]/index.ts
  src/pages/api/v1/company/[companyId]/report_financial/[reportId]/index.ts
  src/pages/api/v1/company/[companyId]/report_financial/index.ts
  src/pages/api/v1/company/[companyId]/salary/folder/index.ts
  src/pages/users/reports/financials/view/[reportId].tsx
Labels: enhancement, 2

#1617 Feature/refactor generate report
  package.json
  src/interfaces/report.ts
  src/lib/utils/formatter/report.formatter.ts
  src/lib/utils/repo/report.repo.ts
  src/lib/utils/type_guard/account.ts
  src/pages/api/v1/company/[companyId]/account/index.ts
  src/pages/api/v1/company/[companyId]/report_financial/[reportId]/index.ts
  src/pages/api/v1/company/[companyId]/report_financial/index.ts
  src/pages/api/v1/company/[companyId]/report_generated/index.test.ts
  src/pages/api/v1/company/[companyId]/report_generated/index.ts
  src/pages/api/v1/company/[companyId]/report_pending/index.test.ts
  src/pages/api/v1/company/[companyId]/report_pending/index.ts
Labels: enhancement, 3

#1656 add translate
  src/components/financial_report_section/financial_report_section.tsx
  src/constants/report.ts
  src/interfaces/report.ts
  src/locales/cn/common.json
  src/locales/en/common.json
  src/locales/tw/common.json
  src/pages/api/v1/company/[companyId]/report_financial/index.ts
Labels: enhancement, 3

#1661 Feature/put seperate
  package.json
  src/interfaces/invoice.ts
  src/lib/utils/formatter/invoice.formatter.ts
  src/lib/utils/repo/invoice.repo.ts
  src/lib/utils/repo_test/invoice.repo.test.ts
  src/pages/api/v1/company/[companyId]/invoice/[invoiceId]/index.ts
Labels: enhancement, 5

#1688 Feature/account refactor
  package.json
  prisma/seed.ts
  prisma/seed_json/account.json
  src/constants/account.ts
  src/constants/account_sheet_mapping/balance_sheet_lite_mapping.json
  src/constants/cash_flow/operating_cash_flow.ts
  src/constants/report.ts
  src/contexts/accounting_context.tsx
  src/interfaces/accounting_account.ts
  src/lib/utils/account/abstract_account_retriever.ts
  src/lib/utils/account/account_retriever_factory.ts
  src/lib/utils/account/asset_account_retriever.ts
  src/lib/utils/account/balance_sheet_account_retriever.ts
  src/lib/utils/account/common.ts
  src/lib/utils/account/equity_account_retriever.ts
  src/lib/utils/account/general_account_retriever.ts
  src/lib/utils/account/income_statement_account_retriever.ts
  src/lib/utils/account/liability_account_retriever.ts
  src/lib/utils/financial_report/balance_sheet_generator.ts
  src/lib/utils/financial_report/cash_flow_statement_generator.ts
  src/lib/utils/financial_report/financial_report_generator.ts
  src/lib/utils/financial_report/income_statement_generator.ts
  src/lib/utils/formatter/account.formatter.ts
  src/lib/utils/formatter/report.formatter.ts
  src/lib/utils/repo/account.repo.ts
  src/lib/utils/type_guard/account.ts
  src/pages/api/v1/company/[companyId]/account/[accountId]/index.test.ts
  src/pages/api/v1/company/[companyId]/account/index.test.ts
  src/pages/api/v1/company/[companyId]/account/index.ts
  src/pages/api/v1/company/[companyId]/invoice/[invoiceId]/index.ts
  src/pages/api/v1/company/[companyId]/report_generated/index.ts
  src/pages/api/v1/company/[companyId]/report_pending/index.ts
Labels: enhancement, 8

#1727 fix: journal list item credit, debit unbalance, account won't return all accounts, report_financial add start and end time
  package.json
  src/constants/account_sheet_mapping/cash_flow_statement_mapping.json
  src/constants/cash_flow/operating_cash_flow.ts
  src/contexts/accounting_context.tsx
  src/lib/utils/financial_report/cash_flow_statement_generator.ts
  src/lib/utils/financial_report/income_statement_generator.ts
  src/lib/utils/formatter/journal.formatter.ts
  src/lib/utils/line_item.ts
  src/pages/api/v1/company/[companyId]/report_financial/[reportId]/index.ts
  src/pages/api/v1/company/[companyId]/report_financial/index.ts
Labels: bug, 2
